import React, { useState, useEffect } from 'react';
import { useRouter } from 'next/router';

import Head from 'next/head';
import America from '../components/america';

export default function Home() {
  const [left, setLeft] = useState(null);
  const [top, setTop] = useState(null);
  const [none, setNone] = useState(true);
  const [textID, setTextID] = useState(-1);
  const router = useRouter()

  function onMouseMove(e) {
    setNone(false);
    setLeft(e.pageX + 20);
    setTop(e.pageY - 20);
  }

  function showHeadlines(e) {
    window.removeEventListener('mousemove', onMouseMove);
    window.removeEventListener('mouseout', (event) => {
      if (event.clientY <= 0 || event.clientX <= 0 || (event.clientX >= window.innerWidth || event.clientY >= window.innerHeight)) {
        setNone(true);
      }
    });
  }

  useEffect(function mount() {
    window.addEventListener('mousemove', onMouseMove);
    window.addEventListener('mousedown', showHeadlines);
    window.addEventListener('mouseout', (event) => {
      if (event.clientY <= 0 || event.clientX <= 0 || (event.clientX >= window.innerWidth || event.clientY >= window.innerHeight)) {
        setNone(true);
      }
    });
  });

  const handleClick = () => {
    if (textID < 2) {
      setTextID(textID + 1);
    }
    if (textID == 2) {
      router.push('flows/intro');
    }
  };
  const renderPage = () => {
    return (
      <div onClick={handleClick} role="button" tabIndex={0}>
        <America left={left} top={top} none={none} textID={textID} />
      </div>
    );
  }
  return (
    <div>
      <Head>
        <title>Oceanus</title>
        <meta name="description" content="Oceanus generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {renderPage()}
      </main>
    </div>
  )
}
